
export const ApiSlug = {  
    LOGIN :"login.php",
    REGISTER :"register.php",
    FEATCH_USER_PROFILE :"fetch-user-profile.php",
    FEATCH_USER_FOLLOWING :"fetch-user-following.php",
    FEATCH_USER_FOLLOWERS :"fetch-user-followers.php",
    UPDATE_USER_SETUP_DETAILS :"update-user-setup-details.php",
    FETCH_INDIVIDUAL_SKILLS :"fetch-individual-skills.php",
    FETCH_BUSINESS_SKILLS :"fetch-business-skills.php",
    FETCH_ACTIVITY_STREAM :"view-activity-stream.php",
    FETCH_ACTIVITY_DETAILS :"view-post-details.php",
    FETCH_POST_TAGGED_USERS :"fetch-post-tagged-users.php",
    FETCH_POST_COMMENTS :"fetch-post-comments.php",
    ADD_POST_COMMENTS :"add-post-comment.php",
    FETCH_USER_BALANCE :"fetch-user-balance.php",
    FETCH_WALLET_HISTORY :"fetch-wallet-payment-history.php",
    ADD_AMOUNT_WALLET:"add-amount-in-wallet.php",
    PROMOTION_INSIGHTS:"fetch-promotion-insights.php",
    PROMOTION_STATUS_UPDATE:"update-promotion-status.php", 
    ADD_POST:"add-post.php", 
    SEARCH_PEOPLE:"search-people.php", 
}
